server:
  port: 8500

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: borrow-service
        uri: lb://borrowservice
        predicates:
        - Path=/borrow/**

      - id: book-service
        uri: lb://bookservice
        predicates:
        - Path=/book/**
        filters:
        - AddRequestHeader=Test, Fuck World
